export default {
    ADMIN: 'ADMIN',
    AGENT: 'AGENT',
    RESOURCE: 'RESSOURCE',
    OVERSEER: 'CONTROLLEUR',
    ACCOUNTANT: 'COMPATBLE',
    SUPERVISOR: 'SUPERVISEUR',
    COLLECTOR: 'RESPONSABLE DE ZONNE',
    MANAGER: 'GESTIONNAIRE DE FLOTTE',
};