const STORE_ATTEMPT_USER_IDENTIFICATION_REQUEST_INIT = 'STORE_ATTEMPT_USER_IDENTIFICATION_REQUEST_INIT';
const STORE_ATTEMPT_USER_IDENTIFICATION_REQUEST_FAILED = 'STORE_ATTEMPT_USER_IDENTIFICATION_REQUEST_FAILED';
const STORE_ATTEMPT_USER_IDENTIFICATION_REQUEST_SUCCEEDED = 'STORE_ATTEMPT_USER_IDENTIFICATION_REQUEST_SUCCEEDED';

export default {
    STORE_ATTEMPT_USER_IDENTIFICATION_REQUEST_INIT,
    STORE_ATTEMPT_USER_IDENTIFICATION_REQUEST_FAILED,
    STORE_ATTEMPT_USER_IDENTIFICATION_REQUEST_SUCCEEDED,

    // Set init data into store
    storeAttemptUserIdentificationRequestInit: () => ({
        type: STORE_ATTEMPT_USER_IDENTIFICATION_REQUEST_INIT
    }),
    // Set failed data into store
    storeAttemptUserIdentificationRequestFailed: () => ({
        type: STORE_ATTEMPT_USER_IDENTIFICATION_REQUEST_FAILED
    }),
    // Set success data into store
    storeAttemptUserIdentificationRequestSucceeded: () => ({
        type: STORE_ATTEMPT_USER_IDENTIFICATION_REQUEST_SUCCEEDED
    }),
}




